// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8At68ChVXUEy0gh42l3HRWm3LZ0STgPY',
    appId: '1:73984160061:web:e3110629a2813a1844d554',
    messagingSenderId: '73984160061',
    projectId: 'cloud-infotech-576fa',
    authDomain: 'cloud-infotech-576fa.firebaseapp.com',
    storageBucket: 'cloud-infotech-576fa.appspot.com',
    measurementId: 'G-YH67TEQ0YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoJ2tOPEoNR5VIYNHXt_SdfhuFVWg4-nk',
    appId: '1:73984160061:android:a29e81abbed843a544d554',
    messagingSenderId: '73984160061',
    projectId: 'cloud-infotech-576fa',
    storageBucket: 'cloud-infotech-576fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKnZt91hmwCTrMqUbbvdILnbffDsfABAE',
    appId: '1:73984160061:ios:f04f0508cf83877c44d554',
    messagingSenderId: '73984160061',
    projectId: 'cloud-infotech-576fa',
    storageBucket: 'cloud-infotech-576fa.appspot.com',
    iosClientId: '73984160061-d35artlu6kbi8dvahbecom8aor4sangh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudinfotech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKnZt91hmwCTrMqUbbvdILnbffDsfABAE',
    appId: '1:73984160061:ios:f04f0508cf83877c44d554',
    messagingSenderId: '73984160061',
    projectId: 'cloud-infotech-576fa',
    storageBucket: 'cloud-infotech-576fa.appspot.com',
    iosClientId: '73984160061-d35artlu6kbi8dvahbecom8aor4sangh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudinfotech',
  );
}
